on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

env:
  MAIN_BRANCH: refs/heads/main

jobs:
  gitversion:
    name: gitversion
    runs-on: ubuntu-22.04
    steps:
    - name: Calculate changed services
      id: calculate_changed_services
      run: |
        changed_services=`git diff main HEAD --name-only | grep -o '^apps/\w*' | sort | uniq`
        echo "::set-output name=changed_services::$changed_services"
    - name: Calculate service versions
      run: |
        changed_services=( ${{ steps.calculate_changed_services.outputs.changed_services }} )
        for svc in "${changed_services[@]}"; do
          docker run --rm -v "$(pwd):/repo" gittools/gitversion:5.10.0-alpine.3.14-6.0 /repo /config "/repo/${svc}/.gitversion.yml"
        done
